### ISSUE TITLE
Implement Google+ login and authentication

### ISSUE THREAD

**Issue by DrkSephy** [DrkSephy/django-hackathon-starter#1]
To make use of Google's numerous APIs, Google+ authentication is needed. More information on this can be found [here](https://developers.google.com/+/web/signin/).

**Comment by micah-weitzman** [comment]
I'm on it

**Comment by micah-weitzman** [comment]
which way do you want it done? Pure server side?

**Comment by DrkSephy** [comment]
Pure server side. For reference, take a look at this example for Instagram within `scripts/instagram.py`: [example](https://github.com/DrkSephy/django-hackathon-starter/blob/master/hackathon_starter/hackathon/scripts/instagram.py).

**Comment by lsxliron** [comment]
Done
