### ISSUE TITLE
More integration with Django REST framework

### ISSUE THREAD

**Issue by DrkSephy** [DrkSephy/django-hackathon-starter#23]
Currently there is a simple Django Rest framework example for creating Code Snippets and sending a JSON response to the server. It would be good to have a deeper example which supports more features beyond GET requests (PUT, DELETE, UPDATE).

**Comment by decentral1se** [comment]
@DrkSephy, I have created a PR, #25, which addresses this feature.

**Comment by DrkSephy** [comment]
Resolved by PR #25, closing. Thanks!
