### ISSUE TITLE
Python 3 port

### ISSUE THREAD

**Issue by kabaka0** [DrkSephy/django-hackathon-starter#29]
Have not yet quite figured out how to contribute using git (as my profile probably shows!) but in case anyone needs it I ported the app to Python 3.4 (tested with django 1.8.4). 

https://github.com/kabaka0/django-hackathon-starter

Sorry for using 'Issues', I assume it is not the  right forum for this.

One unittest fails though, testGetForkedRepositories(). I currently have it set as skipped. I assume that 'DrkSephy's repositories have changed hence the failure.

**Comment by DrkSephy** [comment]
A Python 3 port won't be possible mainly due to the underlying OAuth libraries not having support for Python 3. I'll be closing this issue, but if there is anything I can do in the future I'll be sure to do so. Thanks!

**Comment by Tirpitz93** [comment]
any hope of reopening this?
I'm looking at: https://pypi.python.org/pypi/oauthlib
and https://pypi.python.org/pypi/oauth2 (version 1.9.0.post1)
