### ISSUE TITLE
Implement Facebook Login

### ISSUE THREAD

**Issue by DrkSephy** [DrkSephy/django-hackathon-starter#3]
One of the most common sign-in methods (Facebook) has not been implemented. Users often fall back to using this method, so it should be a high priority to get it done.

**Comment by DrkSephy** [comment]
For reference, we're currently using [this library](https://github.com/simplegeo/python-oauth2) for handling OAuth.

**Comment by lsxliron** [comment]
Please review the code and merge

**Comment by DrkSephy** [comment]
I don't see a pull request, did you not send one in?

**Comment by lsxliron** [comment]
Sorry. Long day. You should have it now...

**Comment by DrkSephy** [comment]
Regarding the Facebook login, I believe there is a configuration that needs to happen on your end. When trying to log in, this is the error I am getting: 

![app](https://cloud.githubusercontent.com/assets/1226900/7664489/d6fe6acc-fb57-11e4-90c7-178dec8d00c0.png)

**Comment by lsxliron** [comment]
I sent a pull request and changed the app status. Suppose to be working now

**Comment by DrkSephy** [comment]
Implemented by #8
