### ISSUE TITLE
Install TRAVIS

### ISSUE THREAD

**Issue by pyjavo** [DrkSephy/django-hackathon-starter#33]
I think it would be awesome to install [travis.ci](https://github.com/integrations/travis-ci) in this repository for testing purposes, don't you think?

**Comment by DrkSephy** [comment]
Travis would be a good investment in the future - however at the moment there hasn't been any changes to the project or pull requests to add in new features. If I get back into updating this for the latest Django version, I'll be sure to hook up travis.ci. Thanks!
