### ISSUE TITLE
How to access default site on Vagrant

### ISSUE THREAD

**Issue by dbd5** [DrkSephy/django-hackathon-starter#35]
Hello,

I have followed every step and deployed this in a vagrant VM configured with puphpet.
The machine is running apache in Ubuntu, how do I enable the site and log into this default config

Thanks, 

Adam

**Comment by DrkSephy** [comment]
Once you install the requirements from `requirements.txt` and run the Django webserver, it should work. Let me know if you encounter any more difficulties.

**Comment by dbd5** [comment]
Hi,

I've started the Django webserver, It says Starting development server at http://127.0.0.1:8000

Puphpet setup mappings of all virtual hosts to the host machine on http://192.168.58.106/ so I assumed that going to http://192.168.58.106:8000 should work but it doesn't.

Any suggestions will be appreciated.
