### ISSUE TITLE
Update Facebook readme

### ISSUE THREAD

**Issue by DrkSephy** [DrkSephy/django-hackathon-starter#9]
Due to the older Facebook example being removed, I am no longer sure if those steps are correct. Would it be possible to update these steps?

**Comment by lsxliron** [comment]
Can you provide a link? 
I don't know which example is being remove.

**Comment by DrkSephy** [comment]
In the [readme](https://github.com/DrkSephy/django-hackathon-starter/blob/master/README.md) it has steps to an older Facebook example which required an `AppID` and was for posting to a user's wall using the JavaScript SDK. Your example uses Python (which was my original intention). Could you possibly change the Facebook section in the readme to inform the user of how to get the Facebook login/example up and running (i.e the steps to register the application on Facebook, getting keys, etc.)

**Comment by lsxliron** [comment]
Sure.
